function scrollToSection(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth'});}
function showToast(message){const toast=document.getElementById('toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600);}
function rsvp(button){if(button.dataset.rsvp==='yes'){button.dataset.rsvp='no';button.textContent='RSVP';showToast('RSVP removed.');}else{button.dataset.rsvp='yes';button.textContent='Going ✓';showToast('You are marked as going.');}}
function openModal(title,text){document.getElementById('modalTitle').textContent=title;document.getElementById('modalText').textContent=text;document.getElementById('modalBackdrop').classList.add('open');}
function closeModal(event){if(event&&event.target!==document.getElementById('modalBackdrop'))return;document.getElementById('modalBackdrop').classList.remove('open');}
function openEventForm(){document.getElementById('eventFormBackdrop').classList.add('open');}
function closeEventForm(event){if(event&&event.target!==document.getElementById('eventFormBackdrop'))return;document.getElementById('eventFormBackdrop').classList.remove('open');}
function addEvent(event){event.preventDefault();const name=document.getElementById('eventName').value;const dateVal=document.getElementById('eventDate').value;const timeVal=document.getElementById('eventTime').value;const location=document.getElementById('eventLocation').value;const date=new Date(dateVal+'T00:00:00');const month=date.toLocaleString('en-US',{month:'short'}).toUpperCase();const day=String(date.getDate()).padStart(2,'0');const time=new Date('1970-01-01T'+timeVal).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});const article=document.createElement('article');article.className='event-card';article.innerHTML=`<div class="event-date"><span>${month}</span><strong>${day}</strong></div><div class="event-content"><div class="event-topline"><span class="badge">New</span><span>${time}</span></div><h3>${escapeHtml(name)}</h3><p class="location">📍 ${escapeHtml(location)}</p><p>Community event added from the quick event form.</p><div class="event-actions"><button class="primary-btn small" onclick="rsvp(this)">RSVP</button><button class="secondary-btn small" onclick="openModal('${escapeJs(name)}','${escapeJs(name)} at ${escapeJs(location)}.')">Details</button></div></div>`;document.getElementById('eventList').appendChild(article);closeEventForm();event.target.reset();showToast('Event added.');}
function subscribe(){const input=document.getElementById('emailInput');if(!input.value||!input.value.includes('@')){showToast('Enter a valid email address.');return;}showToast('You are subscribed to community updates.');input.value='';}
function escapeHtml(value){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));}
function escapeJs(value){return value.replace(/['\\]/g,m=>'\\'+m);}
function updateCountdown(){const target=new Date('2026-09-19T14:00:00');const now=new Date();const diff=target-now;const el=document.getElementById('countdown');if(diff<=0){el.textContent='Event day is here!';return;}const days=Math.floor(diff/86400000);const hours=Math.floor((diff%86400000)/3600000);el.textContent=`${days} days • ${hours} hours away`;}
updateCountdown();setInterval(updateCountdown,60000);